Avoid race condition in Chrome when adding remote ICE candidates
Error: `DOMException: Error processing ICE candidate` is thrown if
remote ICE candidates are added and `pc.remoteDescription` is not set.

See https://stackoverflow.com/a/42977150